### ISSUE TITLE
[Request - feature] instant go to the selected timer

### ISSUE THREAD

**Issue by robiebab** [ralfvd/nl.bevlogenheid.countdown#11]
Sometimes you have a situation where you have a countdown timer from a other scene and want to trigger it instantly (without the possibility to re-extend the time from a other scene)

**Comment by ralfvd** [comment]
I don't understand what you'd like to achieve. You can set a running timer to '0' seconds, which will trigger a flow which has a 'countdown has reached 0' trigger. 

If that is not what you mean, can you give an example ?

**Comment by robiebab** [comment]
For example 
flow: 1 is triggered based on lux that initate a 15sec countdown, named: test1.
flow: 2 i set test1 to 0 sec countdown (this can potentially interfear with eachother )

my lights operate based on lux as trigger and use your countdown mechanisme for example to buffer. i also use it to switch on the light immediately, it could potentially interfear with eachtother resulting in a unintended  delay of 15 sec for the buffer mechanisme.

**Comment by ralfvd** [comment]
I am trying to understand your request. So basically as an example

Flow 1 : If lux = 10 , then start countdown timer test1 : 15 seconds
Flow 2: if test1=0 ; turn on light

So what happens is the lux = 10, then after 15 seconds the lamp will turn on.

But now there is another trigger, e.g. motion, and then you'd like to turn on the light immediately.

So that would mean Flow 3: when motion detected : set test1 countdown to 0 seconds

Is this the requested scenario?

**Comment by ralfvd** [comment]
@robiebab Can you give an update on the requested scenario ? Otherwise I will close this issue

**Comment by robiebab** [comment]
what i mean is that 0 to -1 = 1sec. potentially if other flows trys to update in that second the countdown will be for example 15 sec instead of 1 sec :)

**Comment by ralfvd** [comment]
I am afraid I am still not following. Please send me a mail at ralfvd AT gmail.com , so we can discuss in more detail. I understand Dutch and English. Thanks.
